### ISSUE TITLE
HTML is not styled correctly for Go 1.19

### ISSUE THREAD

**Issue by Aakanksh-z98** [JohnStarich/go#25]
This is not working out of the box for simple package examples.

Running `gopages` yields html that is not styled, even though the required files are present under lib/godoc in the generated dist folder.

Running `gopages -base "$(pwd)/dist/"` yields html that is styled however, the source code is found to be missing when we try to navigate to it. This may be because the URL ends in `/package_name.go#L5` instead of `/package_name.go.html#L5`, the latter producing well-styled html of the source code.

**Comment by JohnStarich** [comment]
Hey @Aakanksh-z98, thanks for opening.

Which HTTP server are you using, so I could try to reproduce? This works well on the ones I've tried, so would be good to know the edge cases too.

**Comment by JohnStarich** [comment]
@Aakanksh-z98 I think the issue is you're setting `-base` to a file path, when that should be a base URL path instead. The base defaults to `/` for static assets, which requires a full HTTP server (like Nginx or similar) to handle properly.

Closing since I haven't heard back in a while, but feel free to comment. We can always re-open.

**Comment by JohnStarich** [comment]
Also, the `.html` extension is now included in source file links. Hope that helps!
