### ISSUE TITLE
Pipe

### ISSUE THREAD

**Issue by gedw99** [JohnStarich/go#40]
Just saw the pipe examples.

o was thinking about if sone codegen or annotations can make this easier for our meat sticks tapping away .

here is a pretty slick annotations based code generator:

https://github.com/RussellLuo/kun

it’s possible to use this pattern ?

**Comment by JohnStarich** [comment]
Hey @gedw99! I think pipe isn't quite as capable as something like `kun`, so that may be difficult to make a general solution.

I've toyed with the idea of using Go's more recent generics to make pipe functions compile-time safe, though I lack any divine insight to understand how it could work right now. 😉

**Comment by JohnStarich** [comment]
I'll go ahead and close, since the scope of pipe is intended to be quite simple. Maybe it could be expanded later to support generic function types if that becomes feasible.
